// <auto-generated />
using System;
using CafeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008012459_AddWompi")]
    partial class AddWompi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeApi.Models.Cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagenPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen_public_id");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origen");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("precio");

                    b.Property<int>("Presentacion")
                        .HasColumnType("integer")
                        .HasColumnName("presentacion_gramos");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("integer")
                        .HasColumnName("proceso_id");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("VariedadId")
                        .HasColumnType("integer")
                        .HasColumnName("variedad_id");

                    b.HasKey("Id")
                        .HasName("pk_cafes");

                    b.HasIndex("ProcesoId")
                        .HasDatabaseName("ix_cafes_proceso_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_cafes_usuario_id");

                    b.HasIndex("VariedadId")
                        .HasDatabaseName("ix_cafes_variedad_id");

                    b.ToTable("cafes", null, t =>
                        {
                            t.HasCheckConstraint("ck_cafes_precio", "precio > 0");

                            t.HasCheckConstraint("ck_cafes_presentacion_gramos", "presentacion_gramos IN (340, 500)");

                            t.HasCheckConstraint("ck_cafes_stock", "stock >= 0");
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carrito");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_carrito_usuario_id");

                    b.ToTable("carrito", (string)null);
                });

            modelBuilder.Entity("CafeApi.Models.CarritoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("CarritoId")
                        .HasColumnType("integer")
                        .HasColumnName("carrito_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_carrito_producto");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_carrito_producto_producto_id");

                    b.HasIndex("CarritoId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_carrito_producto_carrito_producto");

                    b.ToTable("carrito_producto", null, t =>
                        {
                            t.HasCheckConstraint("ck_carrito_producto_cantidad", "cantidad >= 1");
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("ReferenciaWompi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referencia_wompi");

                    b.Property<decimal>("Total")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("total");

                    b.Property<string>("TransactionIdWompi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id_wompi");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pedido");

                    b.HasIndex("ReferenciaWompi")
                        .IsUnique()
                        .HasDatabaseName("ux_pedido_referencia_wompi")
                        .HasFilter("referencia_wompi <> ''");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedido_usuario_id");

                    b.ToTable("pedido", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_estado", "estado IN ('Pendiente', 'Pagado', 'Rechazado')");
                        });
                });

            modelBuilder.Entity("CafeApi.Models.PedidoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_pedido_producto");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedido_producto_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_pedido_producto_producto_id");

                    b.ToTable("pedido_producto", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_producto_cantidad", "cantidad >= 1");
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_procesos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_procesos_nombre");

                    b.ToTable("procesos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Se retira toda la pulpa y el mucílago con agua antes de secar el grano. Da una taza limpia, brillante y de acidez clara.",
                            Nombre = "Lavado"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Se quita la pulpa pero se deja parte del mucílago, dulce y pegajoso como la miel, durante el secado. Da más dulzor y cuerpo.",
                            Nombre = "Honey"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "La cereza o el grano reposan en tanques controlados antes del secado. Aporta notas frutales, vinosas e intensas.",
                            Nombre = "Fermentado"
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_email");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_rol", "rol IN ('Administrador', 'Cliente')");
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Variedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_variedades");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_variedades_nombre");

                    b.ToTable("variedades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "La variedad más cultivada de Colombia. Desarrollada por Cenicafé para resistir la roya sin perder calidad en taza.",
                            Nombre = "Castillo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Variedad tradicional de porte bajo. Su taza es brillante, con acidez viva y cuerpo medio.",
                            Nombre = "Caturra"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Desarrollada por Cenicafé a partir de Caturra e Híbrido de Timor. Resistente a la roya, de taza equilibrada.",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Una de las variedades originales que llegaron a América. Taza limpia, dulce y delicada.",
                            Nombre = "Típica"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Variedad de Cenicafé de porte alto, con herencia de Típica y Bourbon. Dulce y de buen cuerpo.",
                            Nombre = "Tabi"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Variedad clásica de frutos rojos. Destaca por su dulzor y su cuerpo redondo.",
                            Nombre = "Bourbon Rojo"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Sus frutos maduran amarillos. Taza con dulzor tipo miel y acidez suave.",
                            Nombre = "Bourbon Amarillo"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Variedad rara y muy apreciada en el Huila. Notas florales y frutales de gran complejidad.",
                            Nombre = "Bourbon Rosado"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Exótica y floral, una de las variedades más valoradas del café de especialidad.",
                            Nombre = "Geisha"
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Cafe", b =>
                {
                    b.HasOne("CafeApi.Models.Proceso", "Proceso")
                        .WithMany("Cafes")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafes_procesos_proceso_id");

                    b.HasOne("CafeApi.Models.Usuario", "Usuario")
                        .WithMany("Cafes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafes_usuario_usuario_id");

                    b.HasOne("CafeApi.Models.Variedad", "Variedad")
                        .WithMany("Cafes")
                        .HasForeignKey("VariedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafes_variedades_variedad_id");

                    b.Navigation("Proceso");

                    b.Navigation("Usuario");

                    b.Navigation("Variedad");
                });

            modelBuilder.Entity("CafeApi.Models.Carrito", b =>
                {
                    b.HasOne("CafeApi.Models.Usuario", "Usuario")
                        .WithOne("Carrito")
                        .HasForeignKey("CafeApi.Models.Carrito", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeApi.Models.CarritoProducto", b =>
                {
                    b.HasOne("CafeApi.Models.Carrito", "Carrito")
                        .WithMany("Productos")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_producto_carrito_carrito_id");

                    b.HasOne("CafeApi.Models.Cafe", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_producto_cafes_producto_id");

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CafeApi.Models.Pedido", b =>
                {
                    b.HasOne("CafeApi.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeApi.Models.PedidoProducto", b =>
                {
                    b.HasOne("CafeApi.Models.Pedido", "Pedido")
                        .WithMany("Productos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_producto_pedido_pedido_id");

                    b.HasOne("CafeApi.Models.Cafe", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_producto_cafes_producto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CafeApi.Models.Carrito", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CafeApi.Models.Pedido", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CafeApi.Models.Proceso", b =>
                {
                    b.Navigation("Cafes");
                });

            modelBuilder.Entity("CafeApi.Models.Usuario", b =>
                {
                    b.Navigation("Cafes");

                    b.Navigation("Carrito");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("CafeApi.Models.Variedad", b =>
                {
                    b.Navigation("Cafes");
                });
#pragma warning restore 612, 618
        }
    }
}
