// <auto-generated />
using System;
using CafeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930235612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeApi.Models.Cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagenPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen_public_id");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origen");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("precio");

                    b.Property<int>("Presentacion")
                        .HasColumnType("integer")
                        .HasColumnName("presentacion_gramos");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<int>("VariedadId")
                        .HasColumnType("integer")
                        .HasColumnName("variedad_id");

                    b.HasKey("Id")
                        .HasName("pk_cafes");

                    b.HasIndex("VariedadId")
                        .HasDatabaseName("ix_cafes_variedad_id");

                    b.ToTable("cafes", null, t =>
                        {
                            t.HasCheckConstraint("ck_cafes_precio", "precio > 0");

                            t.HasCheckConstraint("ck_cafes_presentacion_gramos", "presentacion_gramos IN (340, 500)");

                            t.HasCheckConstraint("ck_cafes_stock", "stock >= 0");
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Variedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_variedades");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_variedades_nombre");

                    b.ToTable("variedades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Castillo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Geisha"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Moka"
                        });
                });

            modelBuilder.Entity("CafeApi.Models.Cafe", b =>
                {
                    b.HasOne("CafeApi.Models.Variedad", "Variedad")
                        .WithMany("Cafes")
                        .HasForeignKey("VariedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafes_variedades_variedad_id");

                    b.Navigation("Variedad");
                });

            modelBuilder.Entity("CafeApi.Models.Variedad", b =>
                {
                    b.Navigation("Cafes");
                });
#pragma warning restore 612, 618
        }
    }
}
